Vagrant.configure("2") do |config|
  require 'yaml'
  settings = YAML.load_file 'settings.yml'

  config.vbguest.auto_update = settings['vbguest']['auto_update']
  config.vbguest.no_remote = settings['vbguest']['no_remote']

  config.vm.box = "bento/centos-7.4"
  config.vm.box_check_update = false

  config.vm.network "private_network", ip: settings['ip']
  config.vm.synced_folder "./", "/vagrant", mount_options: ['dmode=777', 'fmode=777'], disabled: true
  
  config.hostsupdater.aliases = settings['hostsupdater']['aliases']

  config.vm.provider "virtualbox" do |vb|
    vb.memory = settings['vb']['memory']
    vb.cpus = settings['vb']['cpus']
    vb.customize ["modifyvm", :id, "--cableconnected1", "on"]
  end

  config.vm.provision "firstRunning", type: "shell", run: "never", path: "first_running.sh"

end
